apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "search-service.fullname" . }}
  labels:
    {{- include "search-service.labels" . | nindent 4 }}
data:
  JAVA_TOOL_OPTIONS: "-Xmx256m -Xms128m -XX:+UseSerialGC -XX:MaxMetaspaceSize=128m"
  SPRING_AUTOCONFIGURE_EXCLUDE: "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration"
