package com.chatflow.chat.service.message;

import com.chatflow.chat.entity.ChatMessageEntity;
import com.chatflow.chat.entity.RoomMemberEntity;
import com.chatflow.common.dto.BaseMessage.MessageType;
import com.chatflow.common.dto.ChatMessage;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

/**
 * {@link MentionTargets} — 본문의 이름을 실제 알림 대상 room_members 행으로 확정하는 규칙.
 *
 * <p>{@link MentionExtractorTest}가 "본문에서 어떤 이름이 불렸나"를 담당하고,
 * 여기서는 "그래서 누구에게 알림이 가나"만 본다.
 */
class MentionTargetsTest {

    private static RoomMemberEntity member(String userId, String username) {
        return RoomMemberEntity.builder().userId(userId).username(username).build();
    }

    private static List<String> usernamesOf(List<RoomMemberEntity> members) {
        return members.stream().map(RoomMemberEntity::getUsername).toList();
    }

    // ── shouldResolveMentions: 조회 자체를 건너뛰는 게이트 ──────────────

    @Nested
    @DisplayName("shouldResolveMentions")
    class ShouldResolveMentions {

        /** 전송 경로 — 타입/본문/파일명/전달여부를 모두 DTO가 들고 있다. */
        private ChatMessage sent(MessageType type, String content, String fileName) {
            return ChatMessage.builder().type(type).content(content).fileName(fileName).build();
        }

        /** 수정 경로 — 본문만 새 것이고 나머지는 저장된 행에서 온다. */
        private ChatMessageEntity stored(String type, String fileName) {
            return ChatMessageEntity.builder().type(type).fileName(fileName).build();
        }

        @Test
        @DisplayName("@가 없으면 false — room_members 조회조차 하지 않게 한다")
        void plainTextSkipsTheLookup() {
            assertThat(MentionTargets.shouldResolveMentions(sent(MessageType.CHAT, "점심 뭐 먹지", null)))
                    .isFalse();
            assertThat(MentionTargets.shouldResolveMentions(sent(MessageType.CHAT, "", null)))
                    .isFalse();
        }

        @Test
        @DisplayName("null 본문도 false — NPE 없이 통과")
        void nullContentIsFalse() {
            assertThat(MentionTargets.shouldResolveMentions(sent(MessageType.CHAT, null, null)))
                    .isFalse();
            assertThat(MentionTargets.shouldResolveMentions(stored("FILE", "a.pdf"), null)).isFalse();
        }

        @Test
        @DisplayName("@가 있으면 true — 해석은 resolve가 한다")
        void atSignOpensTheGate() {
            assertThat(MentionTargets.shouldResolveMentions(sent(MessageType.CHAT, "@bob 확인", null)))
                    .isTrue();
            // 이메일이라 결국 멘션이 아니지만, 게이트는 값싼 사전 필터일 뿐이다.
            assertThat(MentionTargets.shouldResolveMentions(
                    sent(MessageType.CHAT, "bob@phill.park", null))).isTrue();
        }

        @Test
        @DisplayName("서버가 만든 문구는 @가 있어도 false")
        void serverAuthoredTextIsNeverResolved() {
            assertThat(MentionTargets.shouldResolveMentions(
                    sent(MessageType.SYSTEM, "@bob 님이 초대됨", null))).isFalse();
            assertThat(MentionTargets.shouldResolveMentions(stored("JOIN", null), "@bob 입장"))
                    .isFalse();
        }

        @Test
        @DisplayName("캡션 없이 올린 파일의 자동 본문은 false — 파일명은 사용자가 친 문장이 아니다")
        void autoFileCaptionIsNotUserText() {
            // 프론트가 캡션 공백일 때 채우는 형태. "@bob-review.pdf"를 올렸다는 이유로
            // bob에게 푸시가 가면, 아무도 부르지 않은 사람이 호출당한다.
            assertThat(MentionTargets.shouldResolveMentions(
                    sent(MessageType.FILE, "[파일] @bob-review.pdf", "@bob-review.pdf"))).isFalse();
            assertThat(MentionTargets.shouldResolveMentions(
                    stored("FILE", "@bob-review.pdf"), "[파일] @bob-review.pdf")).isFalse();
        }

        @Test
        @DisplayName("사용자가 직접 친 FILE 캡션은 true")
        void typedFileCaptionIsResolved() {
            assertThat(MentionTargets.shouldResolveMentions(
                    sent(MessageType.FILE, "@bob 차트 확인", "chart.pdf"))).isTrue();
            assertThat(MentionTargets.shouldResolveMentions(
                    stored("FILE", "chart.pdf"), "@bob 차트 확인")).isTrue();
        }

        @Test
        @DisplayName("완전일치라, '[파일] '로 시작하는 진짜 캡션은 잘라먹지 않는다")
        void aTypedCaptionThatMerelyLooksAutoGeneratedStillResolves() {
            // 파일명이 "@bob 봐줘"일 리 없으므로 자동 캡션과 구별된다.
            assertThat(MentionTargets.shouldResolveMentions(
                    sent(MessageType.FILE, "[파일] @bob 봐줘", "chart.pdf"))).isTrue();
            // 접두사만 맞고 파일명이 다른 경우도 사용자가 손댄 것으로 본다.
            assertThat(MentionTargets.shouldResolveMentions(
                    sent(MessageType.FILE, "[파일] @bob-review.pdf 확인", "@bob-review.pdf")))
                    .isTrue();
        }

        @Test
        @DisplayName("자동 캡션 규칙은 FILE에만 적용된다 — CHAT 본문은 그대로 해석")
        void theAutoCaptionRuleIsScopedToFiles() {
            assertThat(MentionTargets.shouldResolveMentions(
                    sent(MessageType.CHAT, "[파일] @bob-review.pdf", "@bob-review.pdf"))).isTrue();
        }

        @Test
        @DisplayName("전달된 글의 @는 멘션이 아니다 — 전달자가 부른 게 아니다")
        void forwardedTextNamesNobody() {
            // 프론트가 "[전달] <보낸이>: <원문>"으로 재조립한다
            // (message_send_helper.dart forwardMessage). 전달자가 친 글자는 없다.
            ChatMessage forwarded = ChatMessage.builder()
                    .type(MessageType.CHAT)
                    .content("[전달] alice: @bob 이거 봐줘")
                    .forwardedFrom("alice: @bob 이거 봐줘")
                    .build();

            assertThat(MentionTargets.shouldResolveMentions(forwarded)).isFalse();
        }

        @Test
        @DisplayName("캡션 없는 파일을 전달해도 파일명 속 @가 되살아나지 않는다")
        void forwardingAFileDoesNotRevivePrefixedFilenames() {
            // 재조립 때문에 본문이 "[파일] <파일명>" 완전일치를 빠져나간다.
            // 전달 규칙이 없으면 여기서 자동 캡션 판정이 뚫린다.
            ChatMessage forwarded = ChatMessage.builder()
                    .type(MessageType.FILE)
                    .content("[전달] alice: [파일] @bob-review.pdf")
                    .fileName("@bob-review.pdf")
                    .forwardedFrom("alice: [파일] @bob-review.pdf")
                    .build();

            assertThat(MentionTargets.shouldResolveMentions(forwarded)).isFalse();
        }

        @Test
        @DisplayName("수정 경로도 전달 메시지는 해석하지 않는다")
        void editingAForwardedMessageResolvesNothing() {
            ChatMessageEntity entity = ChatMessageEntity.builder()
                    .type("CHAT")
                    .forwardedFrom("alice: @bob 이거 봐줘")
                    .build();

            assertThat(MentionTargets.shouldResolveMentions(entity, "[전달] alice: @bob 봐줘"))
                    .isFalse();
        }

        @Test
        @DisplayName("forwardedFrom이 빈 문자열이면 전달이 아니다 — 일반 메시지로 해석")
        void blankForwardedFromIsNotAForward() {
            assertThat(MentionTargets.shouldResolveMentions(ChatMessage.builder()
                    .type(MessageType.CHAT).content("@bob 확인").forwardedFrom("  ").build()))
                    .isTrue();
            assertThat(MentionTargets.shouldResolveMentions(
                    ChatMessageEntity.builder().type("CHAT").forwardedFrom("").build(), "@bob 확인"))
                    .isTrue();
        }
    }

    // ── resolve: 대상 확정 ─────────────────────────────────────────────

    @Nested
    @DisplayName("resolve")
    class Resolve {

        @Test
        @DisplayName("호명된 멤버만 돌려준다")
        void returnsOnlyTheNamedMembers() {
            List<RoomMemberEntity> members = List.of(
                    member("u1", "alice"), member("u2", "bob"), member("u3", "carol"));

            List<RoomMemberEntity> resolved =
                    MentionTargets.resolve(members, "@bob @carol 확인 부탁", "alice");

            assertThat(usernamesOf(resolved)).containsExactly("bob", "carol");
        }

        @Test
        @DisplayName("작성자 본인 멘션은 대상이 아니다")
        void authorNeverNotifiesThemselves() {
            List<RoomMemberEntity> members = List.of(member("u1", "alice"), member("u2", "bob"));

            List<RoomMemberEntity> resolved =
                    MentionTargets.resolve(members, "@alice @bob 나도 나를", "alice");

            assertThat(usernamesOf(resolved)).containsExactly("bob");
        }

        @Test
        @DisplayName("작성자 이름이 다른 멤버 이름을 삼키지 않는다 (매칭 전에 후보에서 제외)")
        void authorNameDoesNotSwallowAShorterMember() {
            // 최장일치라 후보에 "bob smith"가 남아 있으면 "@bob smith 확인"이 통째로
            // 작성자 멘션이 되고, 제거된 뒤에는 bob이 아무 알림도 못 받는다.
            List<RoomMemberEntity> members =
                    List.of(member("u1", "bob smith"), member("u2", "bob"));

            List<RoomMemberEntity> resolved =
                    MentionTargets.resolve(members, "@bob smith 확인해줘", "bob smith");

            assertThat(usernamesOf(resolved)).containsExactly("bob");
        }

        @Test
        @DisplayName("정규식이 잘라먹던 이름들 — 공백/하이픈 UUID/30자 초과")
        void namesNoCharacterClassCouldDescribe() {
            String uuid = "bd515969-a57e-4cc1-b72d-6b2508b483d0";
            String long45 = "a".repeat(45);
            List<RoomMemberEntity> members = List.of(
                    member("u1", "Phill Park"), member("u2", uuid), member("u3", long45),
                    member("u4", "author"));

            List<RoomMemberEntity> resolved = MentionTargets.resolve(
                    members, "@Phill Park @" + uuid + " @" + long45 + " 확인", "author");

            assertThat(usernamesOf(resolved)).containsExactly("Phill Park", uuid, long45);
        }

        @Test
        @DisplayName("본문에 없는 이름, 이메일, 빈 결과는 빈 리스트")
        void nobodyNamedYieldsEmpty() {
            List<RoomMemberEntity> members = List.of(member("u1", "alice"), member("u2", "bob"));

            assertThat(MentionTargets.resolve(members, "회의 언제 하죠", "alice")).isEmpty();
            assertThat(MentionTargets.resolve(members, "메일은 x@bob 으로", "alice")).isEmpty();
            assertThat(MentionTargets.resolve(members, "@dave 있나요", "alice")).isEmpty();
        }

        @Test
        @DisplayName("멤버 목록이 비었거나 null이면 빈 리스트")
        void noMembersYieldsEmpty() {
            assertThat(MentionTargets.resolve(List.of(), "@bob 확인", "alice")).isEmpty();
            assertThat(MentionTargets.resolve(null, "@bob 확인", "alice")).isEmpty();
        }

        @Test
        @DisplayName("username이 null인 행이 섞여 있어도 NPE 없이 통과한다")
        void nullUsernameRowsAreSafe() {
            // Set.of/copyOf 였다면 contains(null) 에서 NPE가 났을 자리다.
            List<RoomMemberEntity> members = new ArrayList<>(Arrays.asList(
                    member("u1", null), member("u2", "bob")));

            assertThatCode(() -> MentionTargets.resolve(members, "@bob 확인", "alice"))
                    .doesNotThrowAnyException();
            assertThat(usernamesOf(MentionTargets.resolve(members, "@bob 확인", "alice")))
                    .containsExactly("bob");
        }

        @Test
        @DisplayName("작성자 username이 null이어도 멘션 해석은 정상 동작한다")
        void nullAuthorIsSafe() {
            List<RoomMemberEntity> members = List.of(member("u1", "alice"), member("u2", "bob"));

            assertThat(usernamesOf(MentionTargets.resolve(members, "@bob 확인", null)))
                    .containsExactly("bob");
        }

        @Test
        @DisplayName("같은 이름이 두 행이면 두 행 다 알림 대상 (userId가 다르면 다른 사람)")
        void duplicateUsernamesAllResolve() {
            List<RoomMemberEntity> members = List.of(
                    member("u1", "bob"), member("u2", "bob"), member("u3", "author"));

            List<RoomMemberEntity> resolved =
                    MentionTargets.resolve(members, "@bob 확인", "author");

            assertThat(resolved).extracting(RoomMemberEntity::getUserId)
                    .containsExactly("u1", "u2");
        }

        @Test
        @DisplayName("같은 이름을 두 번 불러도 한 번만 대상이 된다")
        void repeatedMentionResolvesOnce() {
            List<RoomMemberEntity> members = List.of(member("u1", "bob"), member("u2", "author"));

            assertThat(MentionTargets.resolve(members, "@bob 아니 @bob 진짜", "author"))
                    .hasSize(1);
        }

        @Test
        @DisplayName("결과 순서는 본문 등장 순서가 아니라 멤버 목록 순서다")
        void ordersByRosterNotByAppearance() {
            List<RoomMemberEntity> members = List.of(
                    member("u1", "alice"), member("u2", "bob"), member("u3", "author"));

            List<RoomMemberEntity> resolved =
                    MentionTargets.resolve(members, "@bob 먼저, @alice 나중", "author");

            assertThat(usernamesOf(resolved)).containsExactly("alice", "bob");
        }
    }
}
