apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-service.fullname" . }}
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
data:
  JAVA_TOOL_OPTIONS: "-Xmx256m -Xms128m -XX:+UseSerialGC -XX:MaxMetaspaceSize=128m"
  JWT_EXPIRATION_MS: {{ .Values.jwtExpirationMs | default "3600000" | quote }}
