// Generated by FlutterFire CLI — manually maintained.
// To regenerate: flutterfire configure --project=chatflow-e9596
//
// Web appId: Go to Firebase Console → Project Settings → Your apps → Web app
// and replace the placeholder below.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9-9ROdtCkb2oxnMViAT_yfHghbtoN9TU',
    appId: '1:1004331287506:android:5c76d72630c27e77b57e0b',
    messagingSenderId: '1004331287506',
    projectId: 'chatflow-e9596',
    storageBucket: 'chatflow-e9596.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-9ROdtCkb2oxnMViAT_yfHghbtoN9TU',
    appId: '1:1004331287506:web:86b5777c3a965d67b57e0b',
    messagingSenderId: '1004331287506',
    projectId: 'chatflow-e9596',
    authDomain: 'chatflow-e9596.firebaseapp.com',
    storageBucket: 'chatflow-e9596.firebasestorage.app',
  );
}
